site_name: Stylus Cache Manager
docs_dir: docs/en
repo_url: https://github.com/cobuilders-xyz/stylus-cm-deploy
edit_uri: edit/main/mkdocs/docs/en
site_url: https://cobuilders-xyz.github.io/stylus-cm-deploy

nav:
  - Welcome: index.md
  - Getting Started:
      - Cache Manager Basics: getting-started/cache-manager-basics.md
  #     - Stylus Cache Manager UI:
  #         - Overview: dummy.md
  #         - Common Interactions: dummy.md
  #         - Alert Settings: dummy.md
  #         - Bidding Automation: dummy.md

  # - Local Deployment:
  #     - Docker Compose:
  #         - Arbitrum Local Testnode:
  #             - Overview: dummy.md
  #             - CM interactions: dummy.md
  #             - Guided Testing: dummy.md
  #         - Stylus Cache Manager UI: dummy.md

theme:
  name: material
  logo: assets/cobuilders-logo.png
  favicon: assets/cobuilders-favicon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: slate
      primary: black
      accent: gray
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - scheme: default
      primary: black
      accent: gray
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
  font:
    text: Roboto
  language: en
  features:
    # - navigation.instant
    # - navigation.instant.progress
    # - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.path
    - toc.follow
    # - toc.integrate
    - navigation.top
    - navigation.tracking
    - navigation.footer
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - search.highlight
    - search.share
    - search.suggest

extra:
  homepage: https://cobuilders.xyz
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  status:
    new: Recently added
    deprecated: Deprecated
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cobuilders-xyz/stylus-cm-deploy
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
