site_name: Stylus Cache Manager UI
docs_dir: docs/en
repo_url: https://github.com/cobuilders-xyz/arb-research
edit_uri: edit/main/mkdocs/docs/en
site_url: https://cobuilders-xyz.github.io/arb-research

nav:
  - Home: index.md
  - Getting Started:
      - Cache Manager Info: getting-started/01-cmUsefulInfo.md
      - Nitro Test Node: getting-started/02-nitroTestNodeRunAndAddresses.md
      - CM interactions: getting-started/03-cacheManagerInteractions.md
      - Guided Testing: getting-started/04-CmGuidedTesting.md
  # - Stylus CM Contracts:
  #     - Overview: stylus-cm-contracts/overview.md
  #     - Local Testing: stylus-cm-contracts/testing.md
  # - System Deployment (WIP):
  #     - Local Deployment: local-deployment/index.md
  #     - Docker Compose:
  #         - Docker Prerequisites: local-deployment/docker-compose/prerequisites.md
  #         - Deployment:
  #             - System Deployment: local-deployment/docker-compose/deployment/system-deployment.md
  #     - Kubernetes:
  #         - Kubernetes Prerequisites: local-deployment/kubernetes/prerequisites.md
  #         - Deployment:
  #             - System Deployment: local-deployment/kubernetes/deployment/system-deployment.md
  # - Repo Structure:
  #     - Repo Structure: repo-structure/index.md

  # - Testnet:
  #     - Overview: testnet/index.md
  #     - Explorers: testnet/explorers.md
  #     - Playground: testnet/playground.md
  #     - Bridge: testnet/bridge.md

theme:
  name: material
  logo: assets/cobuilders-logo.png
  favicon: assets/cobuilders-favicon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: slate
      primary: black
      accent: gray
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
    - scheme: default
      primary: black
      accent: gray
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
  font:
    text: Roboto
  language: en
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    # - navigation.sections
    # - navigation.expand
    - navigation.indexes
    - navigation.path
    - toc.follow
    # - toc.integrate
    - navigation.top
    - navigation.tracking
    - navigation.footer
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - search.highlight
    - search.share
    - search.suggest

extra:
  homepage: https://cobuilders.xyz
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
  status:
    new: Recently added
    deprecated: Deprecated
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ifqbuilder/arb-research
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.tabbed:
      alternate_style: true
